# Generated by Django 6.0.7 on 2026-08-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parts',
            new_name='parts_count',
        ),
    ]
